export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'
export const SUBMIT_DRAWER_CREATE_USER = 'SUBMIT_DRAWER_CREATE_USER'
export const SUBMIT_DRAWER_EDIT_USER = 'SUBMIT_DRAWER_EDIT_USER'

//===============> EDIT_MOVIE
export const SUBMIT_DRAWER_EDIT_MOVIE = 'SUBMIT_DRAWER_EDIT_MOVIE'
